-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id serial NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    city character varying(50) COLLATE pg_catalog."default",
    state character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT customers_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_pk serial NOT NULL,
    order_id character varying(8) COLLATE pg_catalog."default",
    order_date date,
    amount integer,
    paymentmode character varying(50) COLLATE pg_catalog."default",
    quantity integer,
    customer_id integer,
    product_id integer,
    price double precision,
    CONSTRAINT orders_pkey PRIMARY KEY (order_pk)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id serial NOT NULL,
    category character varying(50) COLLATE pg_catalog."default",
    sub_category character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.revenue
(
    revenue_id serial NOT NULL,
    customer_id integer,
    order_pk integer,
    product_id integer,
    cost_per_unit double precision,
    profit integer,
    CONSTRAINT revenue_pkey PRIMARY KEY (revenue_id)
);

ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.revenue
    ADD CONSTRAINT revenue_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.revenue
    ADD CONSTRAINT revenue_order_pk_fkey FOREIGN KEY (order_pk)
    REFERENCES public.orders (order_pk) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.revenue
    ADD CONSTRAINT revenue_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;